### ISSUE TITLE
Rofi theme

### ISSUE THREAD

**Issue by EliaHKM** [AkashKrDutta/mydotfiles#1]
Hi,
I would like to have your rofi theme in this reddit thread : [https://www.reddit.com/r/unixporn/comments/n0gn1u/bspwm_dracula_my_first_minimalistic_dark_theme/](url)
if you don't mind
thanks in advance

**Comment by AkashKrDutta** [comment]
Hey.
You can find the rofi theme here: https://github.com/AkashKrDutta/mydotfiles/tree/master/.config/polybar/shapes/scripts/rofi

**Comment by AkashKrDutta** [comment]
I updated the repo with a nord theme, for posterity if any one needs the dracula theme it can be found here - https://github.com/AkashKrDutta/mydotfiles/tree/1d54ecee88cd9628d0c1957238441f08ab8905a6
And, the rofi theme here: https://github.com/AkashKrDutta/mydotfiles/tree/1d54ecee88cd9628d0c1957238441f08ab8905a6/.config/polybar/shapes/scripts/rofi

**Comment by EliaHKM** [comment]
Hi.
Can you tell me please where should i put the .rasi files to make rofi's theme works?
